/**
 * tts_simple.h - Voice prompt player for Box2Robot CAM
 *
 * Plays pre-recorded PCM clips (16kHz, 16bit, mono) via ES8311 I2S.
 * Clips generated by scripts/generate_voice.py using edge-tts.
 * Data embedded in flash via CMakeLists.txt EMBED_FILES.
 */
#pragma once

#include <atomic>
#include <cstring>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "driver/i2s_std.h"
#include "esp_log.h"
#include "config.h"
#include "voice_clips.h"
#include "runtime_config_cam.h"

static const char* TAG_TTS = "tts";

// I2S TX handle from audio.h
extern i2s_chan_handle_t g_i2s_tx;

// Abort flag: set by stop_audio command to interrupt tts_play_pcm immediately
static std::atomic<bool> g_tts_abort{false};

// es_wr() is static in audio.h but visible in the same translation unit
// (main.cpp includes audio.h before tts_simple.h)

// ============ TTS volume helper ============
// TTS 直接使用 dac_volume — 不再单独维护 tts_volume，避免播放时音量跳变
// 如需独立 TTS 音量，从 server 同时设置 dac_volume 和 tts_volume 保持一致
static void tts_set_volume() {
    // 确保 REG32 是当前 dac_volume (防止被其他路径改掉)
    es_wr(0x32, g_cfg_dac_volume);
}
static void tts_restore_volume() {
    // no-op: TTS 用的就是 dac_volume，无需恢复
}

// ============ Core playback ============

// Play raw PCM data (mono 16bit 16kHz) through speaker as stereo I2S
// Checks g_tts_abort each chunk — stop_audio command can interrupt playback in ~8ms
static void tts_play_pcm(const uint8_t* data, uint32_t size) {
    if (!g_i2s_tx || !data || size == 0) return;

    const int16_t* samples = (const int16_t*)data;
    int total_samples = size / 2;
    const int chunk = 128;
    int16_t stereo[128 * 2];  // Stack: 512 bytes (safe, TTS task has 4KB stack)
    size_t written = 0;

    for (int i = 0; i < total_samples; i += chunk) {
        if (g_tts_abort.load()) {
            ESP_LOGI(TAG_TTS, "Playback aborted at %d/%d samples", i, total_samples);
            g_tts_abort = false;
            break;
        }
        int n = (total_samples - i < chunk) ? (total_samples - i) : chunk;
        for (int j = 0; j < n; j++) {
            stereo[j * 2]     = samples[i + j];  // Left
            stereo[j * 2 + 1] = samples[i + j];  // Right (duplicate mono)
        }
        i2s_channel_write(g_i2s_tx, stereo, n * 4, &written, pdMS_TO_TICKS(1000));
    }
}

// Short silence between clips
static void tts_silence(int ms) {
    if (!g_i2s_tx || ms <= 0) return;
    static int16_t zeros[128 * 2] = {};
    size_t written = 0;
    int total = AUDIO_SAMPLE_RATE * ms / 1000;
    for (int i = 0; i < total; i += 128) {
        int n = (total - i < 128) ? (total - i) : 128;
        i2s_channel_write(g_i2s_tx, zeros, n * 4, &written, pdMS_TO_TICKS(500));
    }
}

// Play a voice clip
static void tts_play_clip(const voice_clip_t* clip) {
    if (!clip) return;
    tts_play_pcm(clip->data, clip->size);
}

// ============ High-level API ============

// Play a named prompt (e.g. "prompt_wifi_ap")
static void tts_play_prompt(const char* name) {
    const voice_clip_t* clip = voice_find_prompt(name);
    if (clip) {
        ESP_LOGI(TAG_TTS, "Playing: %s", name);
        tts_set_volume();
        tts_silence(50);  // 50ms leading silence — prevents pop from volume switch
        tts_play_clip(clip);
        tts_silence(50);  // 50ms trailing silence — clean ending
        tts_restore_volume();
    } else {
        ESP_LOGW(TAG_TTS, "Prompt not found: %s", name);
    }
}

// Speak a digit (0-9)
static void tts_speak_digit(int d) {
    if (d < 0 || d > 9) return;
    tts_play_clip(&VOICE_DIGITS[d]);
    tts_silence(80);  // 80ms gap between digits
}

// Speak a letter (A-Z, case insensitive)
static void tts_speak_letter(char c) {
    if (c >= 'a' && c <= 'z') c -= 32;
    if (c < 'A' || c > 'Z') return;
    tts_play_clip(&VOICE_LETTERS[c - 'A']);
    tts_silence(80);
}

// Speak a string character by character (digits + letters)
static void tts_speak_chars(const char* text) {
    for (int i = 0; text[i]; i++) {
        char c = text[i];
        if (c >= '0' && c <= '9') tts_speak_digit(c - '0');
        else if ((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z')) tts_speak_letter(c);
        else if (c == '_') { tts_play_prompt("word_underscore"); tts_silence(80); }
        else if (c == ' ' || c == '-') tts_silence(200);
    }
}

// ============ Pipeline-specific announcements ============

// AP mode WiFi announcement (called every 3s in provisioning loop)
// Reads "Mingle" then spells out the hex suffix
static void tts_announce_wifi(const char* ap_ssid, const char* password) {
    ESP_LOGI(TAG_TTS, "Announcing WiFi: %s / %s", ap_ssid, password);
    tts_play_prompt("prompt_wifi_ap");       // "请用手机连接WiFi"
    tts_silence(200);
    tts_play_prompt("prompt_wifi_name");     // "WiFi名称是"
    tts_silence(100);

    // Play "Mingle" as a single English word
    tts_play_prompt("word_mingle");
    tts_silence(150);

    // Spell out the suffix (e.g. "_A3B5" part after "Mingle_")
    const char* suffix = ap_ssid;
    const char* underscore = strrchr(ap_ssid, '_');
    if (underscore) suffix = underscore;  // starts from "_"
    tts_speak_chars(suffix);

    tts_silence(300);
    tts_play_prompt("prompt_wifi_pwd");      // "密码是一二三四五六七八"
    tts_silence(300);
    tts_play_prompt("prompt_wifi_open");     // "连接后请打开浏览器..."
}

// Pairing code announcement
static void tts_announce_code(const char* code) {
    ESP_LOGI(TAG_TTS, "Announcing code: %s", code);
    tts_play_prompt("prompt_bind_code");     // "绑定码是"
    tts_silence(200);
    tts_speak_chars(code);                   // spell out digits
    tts_silence(300);
    tts_play_prompt("prompt_bind_wait");     // "请在手机上输入..."
}
