/**
 * voice_clips.h - Voice prompt index for Box2Robot CAM
 * Auto-generated by scripts/generate_voice.py — DO NOT EDIT
 */
#pragma once
#include <stdint.h>
#include <stddef.h>
#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct { const char* name; const uint8_t* data; uint32_t size; } voice_clip_t;

extern const uint8_t VDATA_DIGIT_0[];
extern const unsigned int VDATA_DIGIT_0_SIZE;
extern const uint8_t VDATA_DIGIT_1[];
extern const unsigned int VDATA_DIGIT_1_SIZE;
extern const uint8_t VDATA_DIGIT_2[];
extern const unsigned int VDATA_DIGIT_2_SIZE;
extern const uint8_t VDATA_DIGIT_3[];
extern const unsigned int VDATA_DIGIT_3_SIZE;
extern const uint8_t VDATA_DIGIT_4[];
extern const unsigned int VDATA_DIGIT_4_SIZE;
extern const uint8_t VDATA_DIGIT_5[];
extern const unsigned int VDATA_DIGIT_5_SIZE;
extern const uint8_t VDATA_DIGIT_6[];
extern const unsigned int VDATA_DIGIT_6_SIZE;
extern const uint8_t VDATA_DIGIT_7[];
extern const unsigned int VDATA_DIGIT_7_SIZE;
extern const uint8_t VDATA_DIGIT_8[];
extern const unsigned int VDATA_DIGIT_8_SIZE;
extern const uint8_t VDATA_DIGIT_9[];
extern const unsigned int VDATA_DIGIT_9_SIZE;
extern const uint8_t VDATA_LETTER_A[];
extern const unsigned int VDATA_LETTER_A_SIZE;
extern const uint8_t VDATA_LETTER_B[];
extern const unsigned int VDATA_LETTER_B_SIZE;
extern const uint8_t VDATA_LETTER_C[];
extern const unsigned int VDATA_LETTER_C_SIZE;
extern const uint8_t VDATA_LETTER_D[];
extern const unsigned int VDATA_LETTER_D_SIZE;
extern const uint8_t VDATA_LETTER_E[];
extern const unsigned int VDATA_LETTER_E_SIZE;
extern const uint8_t VDATA_LETTER_F[];
extern const unsigned int VDATA_LETTER_F_SIZE;
extern const uint8_t VDATA_LETTER_G[];
extern const unsigned int VDATA_LETTER_G_SIZE;
extern const uint8_t VDATA_LETTER_H[];
extern const unsigned int VDATA_LETTER_H_SIZE;
extern const uint8_t VDATA_LETTER_I[];
extern const unsigned int VDATA_LETTER_I_SIZE;
extern const uint8_t VDATA_LETTER_J[];
extern const unsigned int VDATA_LETTER_J_SIZE;
extern const uint8_t VDATA_LETTER_K[];
extern const unsigned int VDATA_LETTER_K_SIZE;
extern const uint8_t VDATA_LETTER_L[];
extern const unsigned int VDATA_LETTER_L_SIZE;
extern const uint8_t VDATA_LETTER_M[];
extern const unsigned int VDATA_LETTER_M_SIZE;
extern const uint8_t VDATA_LETTER_N[];
extern const unsigned int VDATA_LETTER_N_SIZE;
extern const uint8_t VDATA_LETTER_O[];
extern const unsigned int VDATA_LETTER_O_SIZE;
extern const uint8_t VDATA_LETTER_P[];
extern const unsigned int VDATA_LETTER_P_SIZE;
extern const uint8_t VDATA_LETTER_Q[];
extern const unsigned int VDATA_LETTER_Q_SIZE;
extern const uint8_t VDATA_LETTER_R[];
extern const unsigned int VDATA_LETTER_R_SIZE;
extern const uint8_t VDATA_LETTER_S[];
extern const unsigned int VDATA_LETTER_S_SIZE;
extern const uint8_t VDATA_LETTER_T[];
extern const unsigned int VDATA_LETTER_T_SIZE;
extern const uint8_t VDATA_LETTER_U[];
extern const unsigned int VDATA_LETTER_U_SIZE;
extern const uint8_t VDATA_LETTER_V[];
extern const unsigned int VDATA_LETTER_V_SIZE;
extern const uint8_t VDATA_LETTER_W[];
extern const unsigned int VDATA_LETTER_W_SIZE;
extern const uint8_t VDATA_LETTER_X[];
extern const unsigned int VDATA_LETTER_X_SIZE;
extern const uint8_t VDATA_LETTER_Y[];
extern const unsigned int VDATA_LETTER_Y_SIZE;
extern const uint8_t VDATA_LETTER_Z[];
extern const unsigned int VDATA_LETTER_Z_SIZE;
extern const uint8_t VDATA_PROMPT_WIFI_AP[];
extern const unsigned int VDATA_PROMPT_WIFI_AP_SIZE;
extern const uint8_t VDATA_PROMPT_WIFI_NAME[];
extern const unsigned int VDATA_PROMPT_WIFI_NAME_SIZE;
extern const uint8_t VDATA_PROMPT_WIFI_PWD[];
extern const unsigned int VDATA_PROMPT_WIFI_PWD_SIZE;
extern const uint8_t VDATA_PROMPT_WIFI_OPEN[];
extern const unsigned int VDATA_PROMPT_WIFI_OPEN_SIZE;
extern const uint8_t VDATA_PROMPT_WIFI_OK[];
extern const unsigned int VDATA_PROMPT_WIFI_OK_SIZE;
extern const uint8_t VDATA_PROMPT_WIFI_FAIL[];
extern const unsigned int VDATA_PROMPT_WIFI_FAIL_SIZE;
extern const uint8_t VDATA_PROMPT_WIFI_CONFIG[];
extern const unsigned int VDATA_PROMPT_WIFI_CONFIG_SIZE;
extern const uint8_t VDATA_PROMPT_WIFI_DISC[];
extern const unsigned int VDATA_PROMPT_WIFI_DISC_SIZE;
extern const uint8_t VDATA_PROMPT_BIND_CODE[];
extern const unsigned int VDATA_PROMPT_BIND_CODE_SIZE;
extern const uint8_t VDATA_PROMPT_BIND_WAIT[];
extern const unsigned int VDATA_PROMPT_BIND_WAIT_SIZE;
extern const uint8_t VDATA_PROMPT_BIND_OK[];
extern const unsigned int VDATA_PROMPT_BIND_OK_SIZE;
extern const uint8_t VDATA_PROMPT_BIND_FAIL[];
extern const unsigned int VDATA_PROMPT_BIND_FAIL_SIZE;
extern const uint8_t VDATA_PROMPT_BOOT[];
extern const unsigned int VDATA_PROMPT_BOOT_SIZE;
extern const uint8_t VDATA_PROMPT_READY[];
extern const unsigned int VDATA_PROMPT_READY_SIZE;
extern const uint8_t VDATA_PROMPT_ERROR[];
extern const unsigned int VDATA_PROMPT_ERROR_SIZE;
extern const uint8_t VDATA_PROMPT_BTN_RESET[];
extern const unsigned int VDATA_PROMPT_BTN_RESET_SIZE;
extern const uint8_t VDATA_PROMPT_CAMERA_OK[];
extern const unsigned int VDATA_PROMPT_CAMERA_OK_SIZE;
extern const uint8_t VDATA_PROMPT_AUDIO_OK[];
extern const unsigned int VDATA_PROMPT_AUDIO_OK_SIZE;
extern const uint8_t VDATA_PROMPT_SERVER_OK[];
extern const unsigned int VDATA_PROMPT_SERVER_OK_SIZE;
extern const uint8_t VDATA_PROMPT_SERVER_FAIL[];
extern const unsigned int VDATA_PROMPT_SERVER_FAIL_SIZE;
extern const uint8_t VDATA_PROMPT_SERVER_DISC[];
extern const unsigned int VDATA_PROMPT_SERVER_DISC_SIZE;
extern const uint8_t VDATA_PROMPT_LISTEN[];
extern const unsigned int VDATA_PROMPT_LISTEN_SIZE;
extern const uint8_t VDATA_PROMPT_THINKING[];
extern const unsigned int VDATA_PROMPT_THINKING_SIZE;
extern const uint8_t VDATA_PROMPT_BYE[];
extern const unsigned int VDATA_PROMPT_BYE_SIZE;
extern const uint8_t VDATA_PROMPT_OTA_DOWNLOAD[];
extern const unsigned int VDATA_PROMPT_OTA_DOWNLOAD_SIZE;
extern const uint8_t VDATA_PROMPT_OTA_FLASH[];
extern const unsigned int VDATA_PROMPT_OTA_FLASH_SIZE;
extern const uint8_t VDATA_PROMPT_OTA_REBOOT[];
extern const unsigned int VDATA_PROMPT_OTA_REBOOT_SIZE;
extern const uint8_t VDATA_PROMPT_MINGLE_ONCE[];
extern const unsigned int VDATA_PROMPT_MINGLE_ONCE_SIZE;
extern const uint8_t VDATA_PROMPT_BOOT_MINGLE[];
extern const unsigned int VDATA_PROMPT_BOOT_MINGLE_SIZE;
extern const uint8_t VDATA_WORD_MINGLE[];
extern const unsigned int VDATA_WORD_MINGLE_SIZE;
extern const uint8_t VDATA_WORD_UNDERSCORE[];
extern const unsigned int VDATA_WORD_UNDERSCORE_SIZE;

static const voice_clip_t VOICE_DIGITS[] = {
    {"0", VDATA_DIGIT_0, 14080},
    {"1", VDATA_DIGIT_1, 11776},
    {"2", VDATA_DIGIT_2, 8896},
    {"3", VDATA_DIGIT_3, 13568},
    {"4", VDATA_DIGIT_4, 14976},
    {"5", VDATA_DIGIT_5, 15488},
    {"6", VDATA_DIGIT_6, 15616},
    {"7", VDATA_DIGIT_7, 13952},
    {"8", VDATA_DIGIT_8, 10112},
    {"9", VDATA_DIGIT_9, 15296},
};
#define VOICE_DIGITS_COUNT 10

static const voice_clip_t VOICE_LETTERS[] = {
    {"A", VDATA_LETTER_A, 11904},
    {"B", VDATA_LETTER_B, 11456},
    {"C", VDATA_LETTER_C, 15168},
    {"D", VDATA_LETTER_D, 10368},
    {"E", VDATA_LETTER_E, 12416},
    {"F", VDATA_LETTER_F, 12608},
    {"G", VDATA_LETTER_G, 12352},
    {"H", VDATA_LETTER_H, 18368},
    {"I", VDATA_LETTER_I, 11584},
    {"J", VDATA_LETTER_J, 13120},
    {"K", VDATA_LETTER_K, 12416},
    {"L", VDATA_LETTER_L, 13760},
    {"M", VDATA_LETTER_M, 13568},
    {"N", VDATA_LETTER_N, 9344},
    {"O", VDATA_LETTER_O, 10496},
    {"P", VDATA_LETTER_P, 12416},
    {"Q", VDATA_LETTER_Q, 17728},
    {"R", VDATA_LETTER_R, 14656},
    {"S", VDATA_LETTER_S, 14848},
    {"T", VDATA_LETTER_T, 13184},
    {"U", VDATA_LETTER_U, 12416},
    {"V", VDATA_LETTER_V, 13952},
    {"W", VDATA_LETTER_W, 18432},
    {"X", VDATA_LETTER_X, 16640},
    {"Y", VDATA_LETTER_Y, 14784},
    {"Z", VDATA_LETTER_Z, 15808},
};
#define VOICE_LETTERS_COUNT 26

static const voice_clip_t VOICE_PROMPTS[] = {
    {"prompt_wifi_ap", VDATA_PROMPT_WIFI_AP, 67200},
    {"prompt_wifi_name", VDATA_PROMPT_WIFI_NAME, 39296},
    {"prompt_wifi_pwd", VDATA_PROMPT_WIFI_PWD, 88448},
    {"prompt_wifi_open", VDATA_PROMPT_WIFI_OPEN, 121152},
    {"prompt_wifi_ok", VDATA_PROMPT_WIFI_OK, 46976},
    {"prompt_wifi_fail", VDATA_PROMPT_WIFI_FAIL, 74944},
    {"prompt_wifi_config", VDATA_PROMPT_WIFI_CONFIG, 54976},
    {"prompt_wifi_disc", VDATA_PROMPT_WIFI_DISC, 107520},
    {"prompt_bind_code", VDATA_PROMPT_BIND_CODE, 30848},
    {"prompt_bind_wait", VDATA_PROMPT_BIND_WAIT, 164800},
    {"prompt_bind_ok", VDATA_PROMPT_BIND_OK, 44672},
    {"prompt_bind_fail", VDATA_PROMPT_BIND_FAIL, 61440},
    {"prompt_boot", VDATA_PROMPT_BOOT, 68608},
    {"prompt_ready", VDATA_PROMPT_READY, 38976},
    {"prompt_error", VDATA_PROMPT_ERROR, 70656},
    {"prompt_btn_reset", VDATA_PROMPT_BTN_RESET, 87808},
    {"prompt_camera_ok", VDATA_PROMPT_CAMERA_OK, 60480},
    {"prompt_audio_ok", VDATA_PROMPT_AUDIO_OK, 64640},
    {"prompt_server_ok", VDATA_PROMPT_SERVER_OK, 48960},
    {"prompt_server_fail", VDATA_PROMPT_SERVER_FAIL, 50368},
    {"prompt_server_disc", VDATA_PROMPT_SERVER_DISC, 61120},
    {"prompt_listen", VDATA_PROMPT_LISTEN, 17664},
    {"prompt_thinking", VDATA_PROMPT_THINKING, 32832},
    {"prompt_bye", VDATA_PROMPT_BYE, 18048},
    {"prompt_ota_download", VDATA_PROMPT_OTA_DOWNLOAD, 83072},
    {"prompt_ota_flash", VDATA_PROMPT_OTA_FLASH, 80640},
    {"prompt_ota_reboot", VDATA_PROMPT_OTA_REBOOT, 70336},
    {"prompt_mingle_once", VDATA_PROMPT_MINGLE_ONCE, 19200},
    {"prompt_boot_mingle", VDATA_PROMPT_BOOT_MINGLE, 16000},
    {"word_mingle", VDATA_WORD_MINGLE, 18240},
    {"word_underscore", VDATA_WORD_UNDERSCORE, 28352},
};
#define VOICE_PROMPTS_COUNT 31

static inline const voice_clip_t* voice_find_prompt(const char* name) {
    for (int i = 0; i < VOICE_PROMPTS_COUNT; i++)
        if (strcmp(VOICE_PROMPTS[i].name, name) == 0) return &VOICE_PROMPTS[i];
    return NULL;
}

#ifdef __cplusplus
}
#endif
